### ISSUE TITLE
 I click signup, Why didn't the uploaded pictures cut? Still the original picture.

### ISSUE THREAD

**Issue by klintlili** [stkevich/yii2-cropper#1]
![default](https://user-images.githubusercontent.com/3251749/32491321-3c2144f6-c3f1-11e7-8c65-8d6c646d735b.png)

![default](https://user-images.githubusercontent.com/3251749/32491355-5b594b0c-c3f1-11e7-8e6d-716a85a0b80c.png)

![default](https://user-images.githubusercontent.com/3251749/32491381-751d22d4-c3f1-11e7-8735-9e8b20c03bb8.png)

I click signup, Why didn't the uploaded pictures cut? Still the original picture.

**Comment by stkevich** [comment]
Added behavior for cropping. Look more at readme.
